### PR TITLE
board.is-an.app

### PR DESCRIPTION
**Pull request by Rahuletto**
# Verification Records

Type | Name | Value
-- | -- | --
TXT | _vercel | vc-domain-verify=board.is-an.app,f8602906e1897b3123cf

### Link to Website

Link: https://cdeboard.vercel.app

---

- [X] Toggle this checkbox to re-run the stargazer checking

I am so sorry to bother you. I wanted to get the `is-an.app` domain but i am unable to do pull request in the real repository by `tarampampam`. I tried ways to contact the owner but i am unable to

image

I saw your pull request being merged recently. So i kindly request you to make a pull request on behalf of me. or tell how to get a domain from it. 

Thanking you
\- Rahul Marban

### CODE REVIEW

**Comment by Rahuletto** [comment]
@Sammy970 just letting you know this pr exists

**Comment by Sammy970** [comment]
> @Sammy970 just letting you know this pr exists

I guess you need to fork and PR to the original repo

**Comment by Rahuletto** [comment]
As I said earlier, I do not have access to do pr in original repo as the owner restricts to previous contributors (you are the latest one of them)

**Comment by Rahuletto** [comment]
I think you wont help me with it. Thanks

**Pull request closed without merging**
